services:
  cats-dogs-api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-cats-dogs-mlops:latest}
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
